import { ThemeProvider } from '@mui/material';
import {
  act,
  fireEvent,
  render,
  renderHook,
  screen,
} from '@testing-library/react';
import { useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';


import { BackOfficeVerifyEmployeeCode } from './BackOfficeVerifyEmployeeCode';

import { useLogInMutation } from 'api/employeeLogInApi';
import { theme } from 'theme/theme';
import { getEmailRoleFromToken } from 'utils/getEmailFromToken';

const mockedGetEmailRoleFromToken = getEmailRoleFromToken as jest.Mock;

jest.mock('api/employeeLogInApi', () => ({
  useLogInMutation: jest.fn(),
}));
jest.mock('react-router-dom', () => ({
  ...jest.requireActual('react-router-dom'),
  useNavigate: jest.fn(),
  useLocation: jest.fn(),
}));
jest.mock('utils/storageAuthHandler', () => ({
  setEmployeeAuthData: jest.fn(),
}));
jest.mock('utils/getEmailFromToken', () => ({
  getEmailRoleFromToken: jest.fn(),
}));

describe('BackOfficeVerifyEmployeeCode', () => {
  let mockLogIn: jest.Mock;
  const mockNavigate = jest.fn();
  const mockLocation = { state: { email: 'test-email@example.com' } };

  beforeEach(() => {
    jest.clearAllMocks();
    mockLogIn = jest.fn();
    (useLogInMutation as jest.Mock).mockReturnValue([
      mockLogIn,
      { isLoading: false },
    ]);
    (useNavigate as jest.Mock).mockReturnValue(mockNavigate);
    (useLocation as jest.Mock).mockReturnValue(mockLocation);

    render(
      <ThemeProvider theme={theme}>
        <BackOfficeVerifyEmployeeCode />
      </ThemeProvider>,
    );
  });

  it('should update OTP state and focus next input when valid numeric value entered', () => {
    const { result } = renderHook(() => {
      const [otp, setOtp] = useState<string[]>(new Array(6).fill(''));
      const inputRefs = useRef<(HTMLInputElement | null)[]>(
        Array(6).fill(null),
      );
      return { otp, setOtp, inputRefs };
    });

    const mockInputRefs = Array(6).fill({ focus: jest.fn() });
    result.current.inputRefs.current = mockInputRefs;

    const handleChange = (value: string, index: number) => {
      if (!/^\d*$/.test(value)) return;
      const newOtp = [...result.current.otp];
      newOtp[index] = value;
      result.current.setOtp(newOtp);
      if (value && index < result.current.otp.length - 1) {
        result.current.inputRefs.current[index + 1]?.focus();
      }
    };

    act(() => {
      handleChange('1', 0);
    });

    expect(result.current.otp[0]).toBe('1');
    expect(mockInputRefs[1].focus).toHaveBeenCalled();
  });

  it('should not update OTP state when non-numeric value entered', () => {
    const { result } = renderHook(() => {
      const [otp, setOtp] = useState<string[]>(new Array(6).fill(''));
      const inputRefs = useRef<(HTMLInputElement | null)[]>(
        Array(6).fill(null),
      );
      return { otp, setOtp, inputRefs };
    });

    const initialOtp = [...result.current.otp];

    const handleChange = (value: string, index: number) => {
      if (!/^\d*$/.test(value)) return;
      const newOtp = [...result.current.otp];
      newOtp[index] = value;
      result.current.setOtp(newOtp);
    };

    act(() => {
      handleChange('a', 0);
    });

    expect(result.current.otp).toEqual(initialOtp);
  });

  it('renders correctly and matches snapshot', () => {
    const { asFragment } = render(
      <ThemeProvider theme={theme}>
        <BackOfficeVerifyEmployeeCode />
      </ThemeProvider>,
    );
    expect(asFragment()).toMatchSnapshot();
  });

  it('renders the form and submits correctly', async () => {
    const mockTokenResponse = { accessToken: 'mock-token' };
    mockLogIn.mockResolvedValue({ data: mockTokenResponse });
    mockedGetEmailRoleFromToken.mockReturnValue({
      email: 'test-email@example.com',
      role: 'admin',
    });

    expect(screen.getByTestId('logo')).toBeInTheDocument();
    expect(
      screen.getByText('Please, fill an OTP code generated by the Google Authenticator app'),
    ).toBeInTheDocument();

    const otpInputs = screen.getAllByRole('textbox');
    expect(otpInputs).toHaveLength(6);

    const confirmButton = screen.getByRole('button', {
      name: 'Confirm',
    });
    expect(confirmButton).toBeDisabled();

    const cancelButton = screen.getByRole('button', {
      name: 'Cancel',
    });
    expect(cancelButton).toBeInTheDocument();

    await act(async () => {
      otpInputs.forEach((input, index) => {
        fireEvent.change(input, { target: { value: String(index + 1) } });
      });
    });

    expect(confirmButton).not.toBeDisabled();

    fireEvent.click(cancelButton);

    await act(async () => {
      otpInputs.forEach((input, index) => {
        fireEvent.change(input, { target: { value: String(index + 1) } });
      });
    });

    await act(async () => {
      fireEvent.click(confirmButton);
    });

    expect(mockLogIn).toHaveBeenCalledWith({
      email: 'test-email@example.com',
      code: '123456',
    });

    await screen.findByRole('button', {
      name: 'Confirm',
    });
  });

  it('should handle backspace key correctly', () => {
    const otpInputs = screen.getAllByRole('textbox');

    otpInputs.forEach((input, index) => {
      fireEvent.change(input, { target: { value: String(index + 1) } });
    });

    fireEvent.keyDown(otpInputs[5], { key: 'Backspace' });
    expect(otpInputs[5]).toHaveValue('');

    fireEvent.keyDown(otpInputs[5], { key: 'Backspace' });
    expect(document.activeElement).toBe(otpInputs[4]);
  });

  it('should call the cancel button handler and reset OTP inputs', () => {
    const otpInputs = screen.getAllByRole('textbox');
    const cancelButton = screen.getByRole('button', {
      name: 'Cancel',
    });

    otpInputs.forEach((input, index) => {
      fireEvent.change(input, { target: { value: String(index + 1) } });
    });

    fireEvent.click(cancelButton);

    otpInputs.forEach((input) => {
      expect(input).toHaveValue('');
    });

    expect(document.activeElement).toBe(otpInputs[0]);
  });

  it('should show loading indicator when submitting OTP', () => {
    (useLogInMutation as jest.Mock).mockReturnValue([
      jest.fn(),
      { isLoading: true },
    ]);

    render(
      <ThemeProvider theme={theme}>
        <BackOfficeVerifyEmployeeCode />
      </ThemeProvider>,
    );

    expect(screen.getByTestId('progress-indicator')).toBeInTheDocument();
  });

  it('should disable confirm button when OTP is incomplete', () => {
    const confirmButton = screen.getByRole('button', {
      name: 'Confirm',
    });

    fireEvent.change(screen.getAllByRole('textbox')[0], {
      target: { value: '1' },
    });

    expect(confirmButton).toBeDisabled();
  });

  it('should not submit if email is missing from location state', async () => {
    (useLocation as jest.Mock).mockReturnValue({ state: null });
    const confirmButton = screen.getByRole('button', {
      name: 'Confirm',
    });

    const otpInputs = screen.getAllByRole('textbox');
    await act(async () => {
      otpInputs.forEach((input, index) => {
        fireEvent.change(input, { target: { value: String(index + 1) } });
      });
    });

    await act(async () => {
      fireEvent.click(confirmButton);
    });

    expect(mockLogIn).not.toHaveBeenCalled();
    expect(mockNavigate).not.toHaveBeenCalled();
  });
});
